# Generated by Django 6.0.2 on 2026-02-27 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Naran Sasan')),
                ('serial', models.CharField(max_length=10, verbose_name='Serial Number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Presu')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Total Tama')),
                ('total_s', models.IntegerField(blank=True, null=True, verbose_name='Total')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('data_sosa', models.DateTimeField(blank=True, null=True, verbose_name='Data SOsa')),
                ('data_prod', models.DateTimeField(blank=True, null=True, verbose_name='Data Produsaun')),
                ('status', models.CharField(blank=True, choices=[('Foun', 'Foun'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('maintenanced', 'maintenanced')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetscreatedbys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetsdeletedbys', to=settings.AUTH_USER_MODEL)),
                ('kat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.sub_kategoria')),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.marka', verbose_name='Marka/Merek')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.supplier', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetsupdatetedbys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '09-Dadus_Assets',
            },
        ),
    ]
